server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  location /admin/ {
    try_files $uri $uri/ /admin/index.html;
  }

  location = /admin {
    return 301 /admin/;
  }
}
